# Generated by Django 5.2.5 on 2025-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_github_url_profile_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("freelancer", "Freelancer"),
                    ("client", "Client"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
