# Generated by Django 5.2.5 on 2025-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientcompany_clientcontact_clientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
